/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsultoriaRouteImport } from './routes/consultoria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiContentRouteImport } from './routes/api/content'
import { Route as ApiAuthRouteImport } from './routes/api/auth'

const ConsultoriaRoute = ConsultoriaRouteImport.update({
  id: '/consultoria',
  path: '/consultoria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentRoute = ApiContentRouteImport.update({
  id: '/api/content',
  path: '/api/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consultoria': typeof ConsultoriaRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/content': typeof ApiContentRoute
  '/api/upload': typeof ApiUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consultoria': typeof ConsultoriaRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/content': typeof ApiContentRoute
  '/api/upload': typeof ApiUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consultoria': typeof ConsultoriaRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/content': typeof ApiContentRoute
  '/api/upload': typeof ApiUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/consultoria' | '/api/auth' | '/api/content' | '/api/upload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/consultoria' | '/api/auth' | '/api/content' | '/api/upload'
  id:
    | '__root__'
    | '/'
    | '/consultoria'
    | '/api/auth'
    | '/api/content'
    | '/api/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultoriaRoute: typeof ConsultoriaRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiContentRoute: typeof ApiContentRoute
  ApiUploadRoute: typeof ApiUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/consultoria': {
      id: '/consultoria'
      path: '/consultoria'
      fullPath: '/consultoria'
      preLoaderRoute: typeof ConsultoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content': {
      id: '/api/content'
      path: '/api/content'
      fullPath: '/api/content'
      preLoaderRoute: typeof ApiContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultoriaRoute: ConsultoriaRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiContentRoute: ApiContentRoute,
  ApiUploadRoute: ApiUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
